name: Build-Deploy-Python-API

on : [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: actions/checkout@v3
      - name: My message
        run: echo "Hello World from Dinesh"