name: Build-Deploy-Python-API

on : [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: $${{secrets.DATABASE_NAME}}
      DATABASE_HOSTNAME: $${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: $${{secrets.DATABASE_PORT}}
      DATABASE_USERNAME: $${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: $${{secrets.DATABASE_PASSWORD}}
      JWT_SECRET_KEY: $${{secrets.JWT_SECRET_KEY}}
      JWT_ALGORITHM: $${{secrets.JWT_ALGORITHM}}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: $${{secrets.JWT_ACCESS_TOKEN_EXPIRE_MINUTES}}
    steps:
      - name: git pull
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install app dependencies
        run: pip install -r requirements.txt
      - name: install and run pytest
        run: |
          pip install pytest
          pytest --disable-warnings -v -s
