name: Deploy-Python-API

on : [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      python-api:
        image: dinbab1984/python-api:latest
        env:
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          DATABASE_HOSTNAME: postgres
          DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
          JWT_ALGORITHM: ${{secrets.JWT_ALGORITHM}}
          JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.JWT_ACCESS_TOKEN_EXPIRE_MINUTES}}
        ports:
          - 8000:8000

    steps:
      - name: Get users from python-api
        run: curl “http://localhost:8000/users"