name: Deploy-Python-API

on : [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: postgres
      env:
        POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        POSTGRES_DB: ${{secrets.DATABASE_NAME}}
      ports:
        - 5432:5432
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      image: ${{ secrets.DOCKER_HUB_USERNAME }}/python-api:latest
    steps:
      - name: Log the node version
        run: echo "Hello World from Postgres Container!!"